version: '3.9'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      APP_DEBUG: "false"
      APP_URL: ${APP_URL}
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      BE_DB_HOST: ${BE_DB_HOST}
      BE_DB_PORT: ${BE_DB_PORT:-3306}
      BE_DB_DATABASE: ${BE_DB_DATABASE}
      BE_DB_USERNAME: ${BE_DB_USERNAME}
      BE_DB_PASSWORD: ${BE_DB_PASSWORD}
      BE_JWT_SECRET: ${BE_JWT_SECRET}
      MAIL_MAILER: smtp
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_ENCRYPTION: ${MAIL_ENCRYPTION:-TLS}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    volumes:
      - backend_storage:/var/www/html/storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VUE_APP_API_URL: ${APP_URL}/
    restart: unless-stopped
    depends_on:
      - backend

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        VUE_APP_API_URL: ${APP_URL}/
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  backend_storage:
